version: "3.7"

services:
  deeppick:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: deeppick
    # volumes:
    #   - ./logs:/home/works/program/logs
    #   - ./conf/online.toml:/home/works/program/conf/online.toml
    restart: always
