// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"encoding/json"
)

type Task struct {
	ID        int32           `json:"id"`
	TaskID    string          `json:"task_id"`
	Status    string          `json:"status"`
	Result    json.RawMessage `json:"result"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}
