// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	sql "database/sql"
)

type Task struct {
	ID        int32
	TaskID    string
	Status    string
	Result    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
